# Generated by Django 3.0.3 on 2020-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
